### ISSUE TITLE
scaling AMD FSR 1.x

### ISSUE THREAD

**Issue by egornovivan** [mattwells77/Fallout_II_Visually_Enhanced_Patch#1]
Please add scaling [FSR](https://github.com/GPUOpen-Effects/FidelityFX-FSR) in patch

**Comment by mattwells77** [comment]
Sorry for the late reply, I will look into this at some point.

**Comment by egornovivan** [comment]
[FidelityFX-SDK](https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK)

**Comment by egornovivan** [comment]
FSR for fallout 2 was implemented through an external wrapper https://github.com/FunkyFr3sh/cnc-ddraw and glsl shaders, support for wrappers was added to sfall. In parallel, work is underway to improve the decompiled versions of Fallout https://github.com/alexbatalov/fallout2-ce

**Comment by egornovivan** [comment]
@mattwells77 Join us in the discord/telegram groups

bgforge
https://discord.gg/4Yqfggm
https://t.me/bgforge

fallout RE/CE
https://discord.gg/qygBRUXuY6
or
https://discord.gg/pgwZY7hDTu
